version: '3.8'

services:
  api-gateway:
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    container_name: ticketing-api-gateway-container
    ports:
      - '8080:8080'
    restart: always

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: ticketing-auth-service-container
    environment:
      - JWT_KEY=jwt-secret
    ports:
      - '8001:8001'
    depends_on:
      - mongodb
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ticketing-client-container
    ports:
      - '3000:3000'
    volumes:
    - ./client:/app
    - /app/node_modules 
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
