apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/auth-depl.yaml
      - infra/k8s/ingress-srv.yaml
      - infra/k8s/auth-mongo-depl.yaml

build:
  local:
    push: false
  artifacts:
    - image: minhajxdd/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
