http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth-api:
    host: 'localhost'
    paths:
      - '/api/users/*'
serviceEndpoints:
  auth-service:
    url: 'http://auth-service:8001'
policies:
  - cors
  - proxy
  - rate-limit
pipelines:
  auth-pipeline:
    apiEndpoints:
      - auth-api
    policies:
      - cors:
          - action:
              origin: 'http://client:3000'
              methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: auth-service
              changeOrigin: true
